"""initial schema

Revision ID: 65cdb55ab127
Revises: 
Create Date: 2026-03-15 18:01:02.110644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cdb55ab127'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_albums', schema=None) as batch_op:
        batch_op.alter_column('monitored',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('override_prefer_synced',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('override_download_covers',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('override_download_lyrics',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('table_artists', schema=None) as batch_op:
        batch_op.alter_column('monitored',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('table_profiles', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('download_covers',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('download_lyrics',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('prefer_synced_lyrics',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('overwrite_existing',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('embed_cover_art',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text("'False'"))

    with op.batch_alter_table('table_tracks', schema=None) as batch_op:
        batch_op.alter_column('hasLyrics',
               existing_type=sa.TEXT(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_tracks', schema=None) as batch_op:
        batch_op.alter_column('hasLyrics',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('table_profiles', schema=None) as batch_op:
        batch_op.alter_column('embed_cover_art',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'False'"))
        batch_op.alter_column('overwrite_existing',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('prefer_synced_lyrics',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('download_lyrics',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('download_covers',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_default',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('table_artists', schema=None) as batch_op:
        batch_op.alter_column('monitored',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('table_albums', schema=None) as batch_op:
        batch_op.alter_column('override_download_lyrics',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('override_download_covers',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('override_prefer_synced',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('monitored',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
